### ISSUE TITLE
What is this ?

### ISSUE THREAD

**Issue by mukhlisakbr** [zhycorp/whatsapp-sticker-bot#2]
You just copied my repository, can't you make it yourself?

[https://github.com/mukhlisakbr/node-whatsapp-sticker-bot](url)

**Comment by mozartrafi** [comment]
Don't mind it, I got a references from others, and so do you too. After all, you did not specify any sufficient LICENSE for this beforehand 😒

**Comment by mukhlisakbr** [comment]
all the contents of index.js and readme are just the same as mine, even the screenshot is mine too

**Comment by mozartrafi** [comment]
Keep in mind that I didn't steal this from you, this kinda published af. I also don't know where we / you got all this from, why are we making a fuss about this?

Ok, I will change this one soon. Don't worry
